#!/usr/bin/env bash

# TODO: need to update credentials to allow push from own machines.
commitmessage='auto - '`whoami`@`hostname`
cd $HOME/dotfiles
/usr/bin/env git push
/usr/bin/env git status -s  | awk '{print $2}'| xargs git add
/usr/bin/env git commit -m "$commitmessage"
/usr/bin/env git pull
/usr/bin/env git push
/usr/bin/env git push origin
/usr/bin/env git push github
/usr/bin/env git push gitlab
/usr/bin/env git push gittea
/usr/bin/env git push --all
/usr/bin/env git pull
echo 'synced dotfiles' >> ~/cron.log
echo $commitmessage >> ~/cron.log
/usr/bin/env git status -s  >> ~/cron.log
