#!/usr/bin/env bash

commitmessage='auto - '`whoami`@`hostname`
cd $HOME/dotfiles
echo 'sync dotfiles' >> ~/cron.log
/usr/bin/env git status -s  | awk '{print $2}'| xargs git add >> ~/cron.log
/usr/bin/env git commit -m "$commitmessage" >> ~/cron.log
echo 'sync dotfiles pull?' >> ~/cron.log
/usr/bin/env git pull >> ~/cron.log
echo 'sync dotfiles push?' >> ~/cron.log
echo 'y no push??? WAT' >> ~/cron.log
whoami >> ~/cron.log
which git >> ~/cron.log
/usr/bin/env git push >> ~/cron.log
git push >> ~/cron.log
echo 'sync dotfiles push origin?' >> ~/cron.log
/usr/bin/env git push origin >> ~/cron.log
echo 'sync dotfiles push github?' >> ~/cron.log
/usr/bin/env git push github >> ~/cron.log
/usr/bin/env git push gitlab >> ~/cron.log
/usr/bin/env git push gittea >> ~/cron.log
/usr/bin/env git push --all >> ~/cron.log
/usr/bin/env git pull >> ~/cron.log
echo 'sync dotfiles done' >> ~/cron.log
