#!/usr/bin/env zsh
alias e="$EDITOR"
alias q=exit
alias c=clear
alias br="bulk-rename"
alias pword='echo $(LC_CTYPE=C tr -dc A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)-+= < /dev/urandom | head -c 32 | xargs)'
alias chromium-no-cors='open -n -a /Applications/Chromium.app/Contents/MacOS/Chromium --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-security'
alias stray_port="lsof -i :"
alias napster='youtube-dl -x --audio-format=mp3'
